name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} для репозитория ${{ github.repository }} успешно выполнен! ${{ github.sha }} - выполнен! ${{ github.event.commit }} - ${{ job.status }}